// Generated by `supabase gen types typescript` against the Bookit production
// project (zhinkdinauylgbkjbwir.supabase.co, ap-south-1).
//
// This is the AUTHORITATIVE schema as it actually exists in Postgres.
// `database.types.ts` next door is the older hand-rolled version that the
// rest of the app still imports — leave that in place so existing imports
// don't break, but if you're writing new code that touches Supabase, prefer
// importing the Database type from here so the types stay in sync with the
// database automatically.
//
// To regenerate after a migration:
//   - Via MCP (this session): `generate_typescript_types` tool
//   - Locally:  `npx supabase gen types typescript --project-id zhinkdinauylgbkjbwir > src/lib/database.generated.ts`

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      audit_log: {
        Row: {
          actor_id: string | null;
          after_state: Json | null;
          before_state: Json | null;
          created_at: string;
          entity_id: string;
          entity_type: string;
          event_type: string;
          id: string;
          ip_address: unknown;
          metadata: Json | null;
          user_agent: string | null;
        };
        Insert: {
          actor_id?: string | null;
          after_state?: Json | null;
          before_state?: Json | null;
          created_at?: string;
          entity_id: string;
          entity_type: string;
          event_type: string;
          id?: string;
          ip_address?: unknown;
          metadata?: Json | null;
          user_agent?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["audit_log"]["Insert"]>;
        Relationships: [];
      };
      booking_equipment: {
        Row: {
          booking_id: string;
          created_at: string;
          currency: string;
          equipment_id: string;
          id: string;
          quantity: number;
          unit_price: number;
        };
        Insert: {
          booking_id: string;
          created_at?: string;
          currency: string;
          equipment_id: string;
          id?: string;
          quantity: number;
          unit_price: number;
        };
        Update: Partial<Database["public"]["Tables"]["booking_equipment"]["Insert"]>;
        Relationships: [];
      };
      bookings: {
        Row: {
          booking_reference: string;
          business_id: string;
          created_at: string;
          customer_email: string | null;
          customer_name: string;
          customer_phone: string | null;
          discount_amount: number;
          id: string;
          notes: string | null;
          payment_amount: number | null;
          payment_currency: string | null;
          payment_method: string | null;
          payment_provider_ref: string | null;
          payment_status: string | null;
          payment_transaction_id: string | null;
          payout_id: string | null;
          payout_status: string | null;
          promo_code_id: string | null;
          provider: string | null;
          provider_initiated_at: string | null;
          provider_invoice_id: string | null;
          provider_payment_url: string | null;
          released_at: string | null;
          service_id: string;
          slot_id: string;
          staff_id: string | null;
          status: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["bookings"]["Row"]> & {
          booking_reference: string;
          business_id: string;
          customer_name: string;
          service_id: string;
          slot_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["bookings"]["Row"]>;
        Relationships: [];
      };
      business_configs: {
        Row: {
          booking_rules_json: Json;
          business_id: string;
          copy_json: Json;
          copy_json_ar: Json | null;
          created_at: string;
          id: string;
          layout_json: Json;
          theme_json: Json;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["business_configs"]["Row"]> & {
          business_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["business_configs"]["Row"]>;
        Relationships: [];
      };
      businesses: {
        Row: {
          address: string | null;
          city: string | null;
          commission_bps: number;
          connected_account_id: string | null;
          country: string | null;
          created_at: string;
          iban_last4: string | null;
          id: string;
          industry: string;
          is_active: boolean;
          lat: number | null;
          lng: number | null;
          logo_url: string | null;
          name: string;
          name_ar: string | null;
          owner_id: string | null;
          payout_provider: string;
          payouts_enabled: boolean;
          phone: string | null;
          postal_code: string | null;
          rejection_reason: string | null;
          slug: string;
          status: string;
          timezone: string | null;
          updated_at: string;
          vat_registered: boolean | null;
          website: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["businesses"]["Row"]> & {
          industry: string;
          name: string;
          slug: string;
        };
        Update: Partial<Database["public"]["Tables"]["businesses"]["Row"]>;
        Relationships: [];
      };
      customer_payment_methods: {
        Row: {
          auto_pay: boolean;
          brand: string;
          cardholder_name: string;
          created_at: string;
          customer_user_id: string;
          exp_month: number;
          exp_year: number;
          id: string;
          is_default: boolean;
          last4: string;
          psp_provider: string;
          psp_token: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["customer_payment_methods"]["Row"]> & {
          brand: string;
          cardholder_name: string;
          customer_user_id: string;
          exp_month: number;
          exp_year: number;
          last4: string;
          psp_token: string;
        };
        Update: Partial<Database["public"]["Tables"]["customer_payment_methods"]["Row"]>;
        Relationships: [];
      };
      equipment: {
        Row: {
          business_id: string;
          category: string;
          created_at: string;
          currency: string;
          description: string | null;
          description_ar: string | null;
          features: string[];
          id: string;
          image_url: string | null;
          is_active: boolean;
          max_per_booking: number;
          name: string;
          name_ar: string | null;
          price: number | null;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["equipment"]["Row"]> & {
          business_id: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["equipment"]["Row"]>;
        Relationships: [];
      };
      reviews: {
        Row: {
          booking_id: string | null;
          business_id: string;
          comment: string | null;
          comment_ar: string | null;
          created_at: string;
          customer_email: string | null;
          customer_name: string;
          id: string;
          is_public: boolean;
          rating: number;
        };
        Insert: Partial<Database["public"]["Tables"]["reviews"]["Row"]> & {
          business_id: string;
          customer_name: string;
          rating: number;
        };
        Update: Partial<Database["public"]["Tables"]["reviews"]["Row"]>;
        Relationships: [];
      };
      services: {
        Row: {
          business_id: string;
          capacity: number;
          color: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          description_ar: string | null;
          duration_minutes: number;
          id: string;
          image_url: string | null;
          is_active: boolean;
          metadata_json: Json;
          name: string;
          name_ar: string | null;
          price: number;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["services"]["Row"]> & {
          business_id: string;
          duration_minutes: number;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["services"]["Row"]>;
        Relationships: [];
      };
      staff: {
        Row: {
          bio: string | null;
          bio_ar: string | null;
          business_id: string;
          created_at: string;
          id: string;
          is_active: boolean;
          metadata_json: Json;
          name: string;
          name_ar: string | null;
          profile_photo_url: string | null;
          rating: number | null;
          role: string | null;
          role_ar: string | null;
          specialty: string | null;
          specialty_ar: string | null;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["staff"]["Row"]> & {
          business_id: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["staff"]["Row"]>;
        Relationships: [];
      };
      time_slots: {
        Row: {
          booked_count: number;
          business_id: string;
          capacity: number;
          created_at: string;
          end_time: string;
          id: string;
          service_id: string | null;
          staff_id: string | null;
          start_time: string;
          status: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["time_slots"]["Row"]> & {
          business_id: string;
          end_time: string;
          start_time: string;
        };
        Update: Partial<Database["public"]["Tables"]["time_slots"]["Row"]>;
        Relationships: [];
      };
      user_roles: {
        Row: {
          granted_at: string;
          granted_by: string | null;
          role: string;
          user_id: string;
        };
        Insert: { granted_at?: string; granted_by?: string | null; role: string; user_id: string };
        Update: Partial<Database["public"]["Tables"]["user_roles"]["Row"]>;
        Relationships: [];
      };
      // Other tables (payouts, ledger_entries, payment_events, promo_codes,
      // waitlist_entries) keep their definitions in database.types.ts;
      // re-generate this file via the MCP tool if you need them fully typed.
    };
    Views: { [_ in never]: never };
    Functions: {
      cancel_booking_atomic: { Args: { p_booking_id: string }; Returns: unknown };
      create_booking_atomic: {
        Args: {
          p_business_id: string;
          p_service_id: string;
          p_staff_id: string;
          p_slot_id: string;
          p_customer_name: string;
          p_customer_phone: string;
          p_customer_email: string;
          p_notes: string;
          p_equipment?: Json;
        };
        Returns: unknown;
      };
      current_user_email: { Args: never; Returns: string };
      current_user_id: { Args: never; Returns: string };
      generate_booking_reference: { Args: never; Returns: string };
      is_business_owner: { Args: { b_id: string }; Returns: boolean };
      is_platform_admin: { Args: never; Returns: boolean };
      join_waitlist: {
        Args: {
          p_business_id: string;
          p_slot_id: string;
          p_customer_name: string;
          p_customer_email: string;
          p_customer_phone: string;
        };
        Returns: unknown;
      };
      redeem_promo_code: {
        Args: {
          p_business_id: string;
          p_code: string;
          p_invoice_amount: number;
          p_currency: string;
        };
        Returns: number;
      };
      release_booking_payout: {
        Args: { p_booking_id: string; p_reason: string; p_actor: string };
        Returns: unknown;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
